version: '3'
services:
  app:
    container_name: springboot-docker
    image: springboot-docker
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: on-failure
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data